let s = document.getElementById("series")
let movies = document.getElementById("Movies")
let series = document.getElementById("active")
let movie = document.getElementById("left")
let first = document.getElementById("first")
let second = document.getElementById("second")
let third = document.getElementById("third")
let forth = document.getElementById("forth")
let fifth = document.getElementById("fifth")
let sixth = document.getElementById("sixth")
let zakhmkari = document.getElementById("zakhmkari")
let joker = document.getElementById("joker")
let aknon = document.getElementById("aknon")
let shamirani = document.getElementById("shamirani")
let momayez = document.getElementById("momayez")
let lala = document.getElementById("lala")
let firstI = document.getElementById("first-img")
let secondI = document.getElementById("second-img")
let thirdI = document.getElementById("third-img")
let forthI = document.getElementById("forth-img")
let fifthI = document.getElementById("fifth-img")
let sixthI = document.getElementById("sixth-img")
movies.style.display = "none"
first.style.width = "180px"
first.style.height = "250px"
firstI.style.width = "180px"
firstI.style.height = "250px"
first.style.border = "3px solid white";
zakhmkari.style.display = "block";
aknon.style.display = "none";
joker.style.display = "none";
shamirani.style.display = "none";
momayez.style.display = "none";
series.style.display = "block";
movie.style.display = "none";
lala.style.display = "none"
function movief() {
    series.style.display = "none";
    s.style.display = "none"
    movie.style.display = "block";
    movies.style.display = "block"
}
function seriesf() {
    movie.style.display = "none"
    movies.style.display = "none";
    series.style.display = "block";
    s.style.display = "block";
}
function firstf() {
    first.style.border = "3px solid white";
    first.style.width = "180px"
    first.style.height = "250px"
    firstI.style.width = "180px"
    firstI.style.height = "250px"
    second.style.border = "none";
    second.style.width = "166px"
    second.style.height = "221px"
    secondI.style.width = "166px"
    secondI.style.height = "221px"
    third.style.border = "none";
    third.style.width = "166px"
    third.style.height = "221px"
    thirdI.style.width = "166px"
    thirdI.style.height = "221px"
    forth.style.border = "none";
    forth.style.width = "166px"
    forth.style.height = "221px"
    forthI.style.width = "166px"
    forthI.style.height = "221px"
    fifth.style.border = "none";
    fifth.style.width = "166px"
    fifth.style.height = "221px"
    fifthI.style.width = "166px"
    fifthI.style.height = "221px"
    sixth.style.border = "none";
    sixth.style.width = "166px"
    sixth.style.height = "221px"
    sixthI.style.width = "166px"
    sixthI.style.height = "221px"
    zakhmkari.style.display = "block";
    aknon.style.display = "none"
    joker.style.display = 'none'
    momayez.style.display = "none";
    shamirani.style.display = "none"
    lala.style.display = "none"
}
function secondf() {
    first.style.border = "none";
    first.style.width = "166px"
    first.style.height = "221px"
    firstI.style.width = "166px"
    firstI.style.height = "221px"
    second.style.border = "3px solid white";
    second.style.width = "180px"
    second.style.height = "250px"
    secondI.style.width = "180px"
    secondI.style.height = "250px"
    third.style.border = "none";
    third.style.width = "166px"
    third.style.height = "221px"
    thirdI.style.width = "166px"
    thirdI.style.height = "221px"
    forth.style.border = "none";
    forth.style.width = "166px"
    forth.style.height = "221px"
    forthI.style.width = "166px"
    forthI.style.height = "221px"
    fifth.style.border = "none";
    fifth.style.width = "166px"
    fifth.style.height = "221px"
    fifthI.style.width = "166px"
    fifthI.style.height = "221px"
    sixth.style.border = "none";
    sixth.style.width = "166px"
    sixth.style.height = "221px"
    sixthI.style.width = "166px"
    sixthI.style.height = "221px"
    joker.style.display = "block"
    zakhmkari.style.display = "none"
    aknon.style.display = "none"
    shamirani.style.display = "none"
    momayez.style.display = "none";
    lala.style.display = "none"
}
function thirdf() {
    first.style.border = "none";
    first.style.width = "166px"
    first.style.height = "221px"
    firstI.style.width = "166px"
    firstI.style.height = "221px"
    zakhmkari.style.display = "none"
    second.style.border = "none";
    second.style.width = "166px"
    second.style.height = "221px"
    secondI.style.width = "166px"
    secondI.style.height = "221px"
    joker.style.display = "none"
    third.style.border = "3px solid white";
    third.style.width = "180px"
    third.style.height = "250px"
    thirdI.style.width = "180px"
    thirdI.style.height = "250px"
    aknon.style.display = "block"
    forth.style.border = "none";
    forth.style.width = "166px"
    forth.style.height = "221px"
    forthI.style.width = "166px"
    forthI.style.height = "221px"
    shamirani.style.display = "none"
    momayez.style.display = "none";
    fifth.style.border = "none";
    fifth.style.width = "166px"
    fifth.style.height = "221px"
    fifthI.style.width = "166px"
    fifthI.style.height = "221px"
    sixth.style.border = "none";
    sixth.style.width = "166px"
    sixth.style.height = "221px"
    sixthI.style.width = "166px"
    sixthI.style.height = "221px"
    lala.style.display = "none"
}
function forthf() {
    first.style.border = "none";
    first.style.width = "166px"
    first.style.height = "221px"
    firstI.style.width = "166px"
    firstI.style.height = "221px"
    zakhmkari.style.display = "none";
    second.style.border = "none";
    second.style.width = "166px"
    second.style.height = "221px"
    secondI.style.width = "166px"
    secondI.style.height = "221px"
    joker.style.display = "none";
    third.style.border = "none";
    third.style.width = "166px"
    third.style.height = "221px"
    thirdI.style.width = "166px"
    thirdI.style.height = "221px"
    aknon.style.display = "none";
    forth.style.border = "3px solid white";
    forth.style.width = "180px"
    forth.style.height = "250px"
    forthI.style.width = "180px"
    forthI.style.height = "250px"
    shamirani.style.display = "block"
    momayez.style.display = "none";
    fifth.style.border = "none";
    fifth.style.width = "166px"
    fifth.style.height = "221px"
    fifthI.style.width = "166px"
    fifthI.style.height = "221px"
    sixth.style.border = "none";
    sixth.style.width = "166px"
    sixth.style.height = "221px"
    sixthI.style.width = "166px"
    sixthI.style.height = "221px"
    lala.style.display = "none"
}
function fifhtf() {
    first.style.border = "none";
    first.style.width = "166px"
    first.style.height = "221px"
    firstI.style.width = "166px"
    firstI.style.height = "221px"
    second.style.border = "none";
    second.style.width = "166px"
    second.style.height = "221px"
    secondI.style.width = "166px"
    secondI.style.height = "221px"
    third.style.border = "none";
    third.style.width = "166px"
    third.style.height = "221px"
    thirdI.style.width = "166px"
    thirdI.style.height = "221px"
    forth.style.border = "none";
    forth.style.width = "166px"
    forth.style.height = "221px"
    forthI.style.width = "166px"
    forthI.style.height = "221px"
    fifth.style.border = "3px solid white";
    fifth.style.width = "180px"
    fifth.style.height = "250px"
    fifthI.style.width = "180px"
    fifthI.style.height = "250px"
    sixth.style.border = "none";
    sixth.style.width = "166px"
    sixth.style.height = "221px"
    sixthI.style.width = "166px"
    sixthI.style.height = "221px"
    momayez.style.display = "block";
    zakhmkari.style.display = "none"
    joker.style.display = "none"
    aknon.style.display = "none"
    shamirani.style.display = "none"
    lala.style.display = "none"
}
function sixthf() {
    first.style.border = "none";
    first.style.width = "166px"
    first.style.height = "221px"
    firstI.style.width = "166px"
    firstI.style.height = "221px"
    second.style.border = "none";
    second.style.width = "166px"
    second.style.height = "221px"
    secondI.style.width = "166px"
    secondI.style.height = "221px"
    third.style.border = "none";
    third.style.width = "166px"
    third.style.height = "221px"
    thirdI.style.width = "166px"
    thirdI.style.height = "221px"
    forth.style.border = "none";
    forth.style.width = "166px"
    forth.style.height = "221px"
    forthI.style.width = "166px"
    forthI.style.height = "221px"
    fifth.style.border = "none";
    fifth.style.width = "166px"
    fifth.style.height = "221px"
    fifthI.style.width = "166px"
    fifthI.style.height = "221px"
    sixth.style.border = "3px solid white";
    sixth.style.width = "180px"
    sixth.style.height = "250px"
    sixthI.style.width = "180px"
    sixthI.style.height = "250px"
    lala.style.display = "block"
    zakhmkari.style.display = "none";
    aknon.style.display = "none"
    joker.style.display = 'none'
    momayez.style.display = "none";
    shamirani.style.display = "none"
}
