let firstM = document.getElementById("firstM")
let secondM = document.getElementById("secondM")
let thirdM = document.getElementById("thirdM")
let forthM = document.getElementById("forthM")
let fifthM = document.getElementById("fifthM")
let sixthM = document.getElementById("sixthM")
let firstIM = document.getElementById("first-M-img")
let secondIM = document.getElementById("second-M-img")
let thirdIM = document.getElementById("third-M-img")
let forthIM = document.getElementById("forth-M-img")
let fifhtIM = document.getElementById("fifth-M-img")
let sixthIM = document.getElementById("sixth-M-img")
let dozakh = document.getElementById("dozakh");
let texas3 = document.getElementById("texas3")
let texas = document.getElementById("texas")
let lone = document.getElementById("lone")
let khorshid = document.getElementById("khorshid")
let nilgon = document.getElementById("nilgon")
firstM.style.border = "3px solid white";
firstIM.style.width = "180px";
firstIM.style.height = "250px";
firstM.style.width = "180px"
firstM.style.height = "250px"
secondM.style.width = "166px"
secondM.style.height = "221px"
thirdM.style.width = "166px"
thirdM.style.height = "221px"
forthM.style.width = "166px"
forthM.style.height = "221px"
fifthM.style.width = "166px"
fifthM.style.height = "221px"
sixthM.style.width = "166px"
sixthM.style.height = "221px"
dozakh.style.display = "block"
texas3.style.display = "none"
texas.style.display = "none"
lone.style.display = "none"
khorshid.style.display = "none"
nilgon.style.display = "none"
function firstF() {
    firstM.style.border = "3px solid white";
    firstIM.style.width = "180px";
    firstIM.style.height = "250px";
    firstM.style.width = "180px"
    firstM.style.height = "250px"
    secondM.style.border = "none";
    secondIM.style.width = "166px";
    secondIM.style.height = "221px";
    secondM.style.width = "166px"
    secondM.style.height = "221px"
    thirdM.style.border = "none";
    thirdIM.style.width = "166px";
    thirdIM.style.height = "221px";
    thirdM.style.width = "166px"
    thirdM.style.height = "221px"
    forthM.style.border = "none";
    forthIM.style.width = "166px";
    forthIM.style.height = "221px";
    forthM.style.width = "166px"
    forthM.style.height = "221px"
    fifthM.style.border = "none";
    fifhtIM.style.width = "166px";
    fifhtIM.style.height = "221px";
    fifthM.style.width = "166px"
    fifthM.style.height = "221px"
    sixthM.style.border = "none";
    sixthIM.style.width = "166px";
    sixthIM.style.height = "221px";
    sixthM.style.width = "166px"
    sixthM.style.height = "221px"
    dozakh.style.display = "block"
    texas3.style.display = "none"
    texas.style.display = "none"
    lone.style.display = "none"
    khorshid.style.display = "none"
    nilgon.style.display = "none"

}
function secondF(params) {
    firstM.style.border = "none";
    firstIM.style.width = "166px";
    firstIM.style.height = "221px";
    firstM.style.width = "166px"
    firstM.style.height = "221px"
    secondM.style.border = "3px solid white";
    secondIM.style.width = "180px";
    secondIM.style.height = "250px";
    secondM.style.width = "180px"
    secondM.style.height = "250px"
    thirdM.style.border = "none";
    thirdIM.style.width = "166px";
    thirdIM.style.height = "221px";
    thirdM.style.width = "166px"
    thirdM.style.height = "221px"
    forthM.style.border = "none";
    forthIM.style.width = "166px";
    forthIM.style.height = "221px";
    forthM.style.width = "166px"
    forthM.style.height = "221px"
    fifthM.style.border = "none";
    fifhtIM.style.width = "166px";
    fifhtIM.style.height = "221px";
    fifthM.style.width = "166px"
    fifthM.style.height = "221px"
    sixthM.style.border = "none";
    sixthIM.style.width = "166px";
    sixthIM.style.height = "221px";
    sixthM.style.width = "166px"
    sixthM.style.height = "221px"
    dozakh.style.display = "none"
    texas3.style.display = "block"
    texas.style.display = "none"
    lone.style.display = "none"
    khorshid.style.display = "none"
    nilgon.style.display = "none"

}
function thirdF(params) {
    firstM.style.border = "none";
    firstIM.style.width = "166px";
    firstIM.style.height = "221px";
    firstM.style.width = "166px"
    firstM.style.height = "221px"
    secondM.style.border = "none";
    secondIM.style.width = "166px";
    secondIM.style.height = "221px";
    secondM.style.width = "166px"
    secondM.style.height = "221px"
    thirdM.style.border = "3px solid white";
    thirdIM.style.width = "180px";
    thirdIM.style.height = "250px";
    thirdM.style.width = "180px"
    thirdM.style.height = "250px"
    forthM.style.border = "none";
    forthIM.style.width = "166px";
    forthIM.style.height = "221px";
    forthM.style.width = "166px"
    forthM.style.height = "221px"
    fifthM.style.border = "none";
    fifhtIM.style.width = "166px";
    fifhtIM.style.height = "221px";
    fifthM.style.width = "166px"
    fifthM.style.height = "221px"
    sixthM.style.border = "none";
    sixthIM.style.width = "166px";
    sixthIM.style.height = "221px";
    sixthM.style.width = "166px"
    sixthM.style.height = "221px"
    texas3.style.display = "none"
    dozakh.style.display = "none"
    texas.style.display = "block"
    lone.style.display = "none"
    khorshid.style.display = "none"
    nilgon.style.display = "none"

}
function forthF(params) {
    firstM.style.border = "none";
    firstIM.style.width = "166px";
    firstIM.style.height = "221px";
    firstM.style.width = "166px"
    firstM.style.height = "221px"
    secondM.style.border = "none";
    secondIM.style.width = "166px";
    secondIM.style.height = "221px";
    secondM.style.width = "166px"
    secondM.style.height = "221px"
    thirdM.style.border = "none";
    thirdIM.style.width = "166px";
    thirdIM.style.height = "221px";
    thirdM.style.width = "166px"
    thirdM.style.height = "221px"
    forthM.style.border = "3px solid white";
    forthIM.style.width = "180px";
    forthIM.style.height = "250px";
    forthM.style.width = "180px"
    forthM.style.height = "250px"
    fifthM.style.border = "none";
    fifhtIM.style.width = "166px";
    fifhtIM.style.height = "221px";
    fifthM.style.width = "166px"
    fifthM.style.height = "221px"
    sixthM.style.border = "none";
    sixthIM.style.width = "166px";
    sixthIM.style.height = "221px";
    sixthM.style.width = "166px"
    sixthM.style.height = "221px"
    dozakh.style.display = "none"
    texas3.style.display = "none"
    texas.style.display = "none"
    lone.style.display = "block"
    khorshid.style.display = "none"
    nilgon.style.display = "none"

}
function fifhtF(params) {
    firstM.style.border = "none";
    firstIM.style.width = "166px";
    firstIM.style.height = "221px";
    firstM.style.width = "166px"
    firstM.style.height = "221px"
    secondM.style.border = "none";
    secondIM.style.width = "166px";
    secondIM.style.height = "221px";
    secondM.style.width = "166px"
    secondM.style.height = "221px"
    thirdM.style.border = "none";
    thirdIM.style.width = "166px";
    thirdIM.style.height = "221px";
    thirdM.style.width = "166px"
    thirdM.style.height = "221px"
    forthM.style.border = "none";
    forthIM.style.width = "166px";
    forthIM.style.height = "221px";
    forthM.style.width = "166px"
    forthM.style.height = "221px"
    fifthM.style.border = "3px solid white";
    fifhtIM.style.width = "180px";
    fifhtIM.style.height = "250px";
    fifthM.style.width = "180px"
    fifthM.style.height = "250px"
    sixthM.style.border = "none";
    sixthIM.style.width = "166px";
    sixthIM.style.height = "221px";
    sixthM.style.width = "166px"
    sixthM.style.height = "221px"
    dozakh.style.display = "none"
    texas3.style.display = "none"
    texas.style.display = "none"
    lone.style.display = "none"
    khorshid.style.display = "block"
    nilgon.style.display = "none"
}
function sixthF(params) {
    firstM.style.border = "none";
    firstIM.style.width = "166px";
    firstIM.style.height = "221px";
    firstIM.style.height = "221px";
    firstM.style.width = "166px"
    secondM.style.border = "none";
    secondIM.style.width = "166px";
    secondIM.style.height = "221px";
    secondM.style.width = "166px"
    secondM.style.height = "221px"
    thirdM.style.border = "none";
    thirdIM.style.width = "166px";
    thirdIM.style.height = "221px";
    thirdM.style.width = "166px"
    thirdM.style.height = "221px"
    forthM.style.border = "none";
    forthIM.style.width = "166px";
    forthIM.style.height = "221px";
    forthM.style.width = "166px"
    forthM.style.height = "221px"
    fifthM.style.border = "none";
    fifhtIM.style.width = "166px";
    fifhtIM.style.height = "221px";
    fifthM.style.width = "166px"
    fifthM.style.height = "221px"
    sixthM.style.border = "3px solid white";
    sixthIM.style.width = "180px";
    sixthIM.style.height = "250px";
    sixthM.style.width = "180px"
    sixthM.style.height = "250px"
    dozakh.style.display = "none"
    texas3.style.display = "none"
    texas.style.display = "none"
    lone.style.display = "none"
    khorshid.style.display = "none"
    nilgon.style.display = "block"
}